# Generated by Django 3.0.2 on 2020-01-26 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200126_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 13, 56, 22, 761079, tzinfo=utc)),
        ),
    ]
